### ISSUE TITLE
No luck with the tool on VDI :-(

### ISSUE THREAD

**Issue by mdd-dsidler** [mPyKen/ScreenAreaShare#16]
Awesome app, thanks for coming up with this!

Unfortunately it's not working as expected when used in a remote desktop session (VMware Horizon). I can somehow define the capture and remoting areas, but I don't see any red border, nor do I see the the window as a selection when sharing in MS Teams.

Given the way these remoting protocols work, is this something that can be fixed at all?

Cheers!

**Comment by mPyKen** [comment]
Hmm interesting use case... I am not sure why it wouldn't work, though, as it's just using electron. Haven't tested it in a remote environment yet

**Comment by mdd-dsidler** [comment]
Thanks for your feedback. Not sure what the issue is exactly, but I tried with a similar tool (https://github.com/tom-englert/RegionToShare) that seems to work somehow in my environment. Just wanted to let you know in case you're interested in a comparison.

**Comment by mPyKen** [comment]
Right, that one is using C# and has access to native layers of windows. This project relies on electron and cannot go beyond that. Although it might be solved by upgrading the electron dependency (since it is using quite an old version). I will see if I can merge https://github.com/mPyKen/ScreenAreaShare/pull/14 which will also upgrade electron

**Comment by mPyKen** [comment]
Just released v1.3.3 - hope the updated dependencies will fix the issue

**Comment by mPyKen** [comment]
I will close this as electron has been updated. If the issue still persists, please open a new one.
